rename namespace to isv.
eclipse-xpanse/xpanse-website pull request #435
Opened 2024-12-18 07:54 UTC by Alice1319

2024-12-18 08:00 UTC, wuzhuanhong commented
LGTM

2024-12-18 08:01 UTC, dengyali0125 commented
LGTM

2024-12-18 08:05 UTC, baixinsui commented
LGTM

2024-12-19 02:33 UTC, profoundwu commented
LGTM

2024-12-20 05:40 UTC, swaroopar requested changes

2024-12-20 05:40 UTC, swaroopar commented on docs/authentication-authorization.mdx
> +With this, users of another isv won't be allowed to view, update or delete these service templates.
here the 'isv' must be written as ISV

2024-12-20 05:40 UTC, swaroopar commented on docs/authentication-authorization.mdx
> +In order to allow service vendors to manage only their own services, we use ABAC. This is achieved by using `metadata` feature of OIDC to assign `isv` users to a specific isv value.
users to a specific ISV value.

2024-12-20 05:40 UTC, swaroopar commented on docs/authentication-authorization.mdx
> +While registering a service, the service vendor must specify the same isv value in the `isv` field.
must specify the same ISV value in the

2024-12-20 06:17 UTC, Alice1319 commented on docs/authentication-authorization.mdx
> +With this, users of another isv won't be allowed to view, update or delete these service templates.
updated.

2024-12-20 06:18 UTC, Alice1319 commented on docs/authentication-authorization.mdx
> +In order to allow service vendors to manage only their own services, we use ABAC. This is achieved by using `metadata` feature of OIDC to assign `isv` users to a specific isv value.
updated.

2024-12-20 06:18 UTC, Alice1319 commented on docs/authentication-authorization.mdx
> +While registering a service, the service vendor must specify the same isv value in the `isv` field.
updated.

2024-12-20 07:20 UTC, swaroopar approved these changes

2024-12-20 07:20 UTC, merged